// packages/svelte/src/lib/spike/a/select/select-content.svelte
<script lang="ts">
	import { Select as SelectPrimitive, type WithoutChild } from 'bits-ui';

	let {
		ref = $bindable(null),
		class: className,
		sideOffset = 4,
		children,
		...restProps
	}: WithoutChild<SelectPrimitive.ContentProps> = $props();
</script>

<SelectPrimitive.Portal>
	<SelectPrimitive.Content bind:ref {sideOffset} {...restProps}>
		{#snippet child({ props, wrapperProps })}
			<div {...wrapperProps}>
				<div {...props} class={['content', className]}>
					<SelectPrimitive.Viewport>
						{#snippet child({ props })}
							<div {...props} class="viewport">
								{@render children?.()}
							</div>
						{/snippet}
					</SelectPrimitive.Viewport>
				</div>
			</div>
		{/snippet}
	</SelectPrimitive.Content>
</SelectPrimitive.Portal>

<style>
	.content {
		position: relative;
		z-index: var(--z-popover);
		min-width: var(--select-content-min-width, 9rem);
		max-height: var(--bits-select-content-available-height);
		overflow-x: hidden;
		overflow-y: auto;
		border-radius: var(--select-content-radius, var(--radius-md));
		background: var(--select-content-bg, var(--color-popover));
		color: var(--select-content-fg, var(--color-popover-foreground));
		box-shadow:
			0 0 0 1px color-mix(in oklch, var(--color-foreground) 10%, transparent),
			var(--shadow-md);
		transform-origin: var(--bits-select-content-transform-origin);
		animation-duration: var(--duration-fast);
		animation-timing-function: var(--ease-out);

		&[data-state='open'] {
			animation-name: distill-zoom-in;
		}

		&[data-state='closed'] {
			animation-name: distill-zoom-out;
		}

		&[data-state='open'][data-side='bottom'] {
			animation-name: distill-zoom-in, distill-slide-in-from-top;
		}

		&[data-state='open'][data-side='top'] {
			animation-name: distill-zoom-in, distill-slide-in-from-bottom;
		}
	}

	.viewport {
		width: 100%;
		min-width: var(--bits-select-anchor-width);
		padding: var(--space-1);
		scroll-margin-block: var(--space-1);
	}
</style>

// packages/vue/src/components/ui/select/SelectContent.vue
<script setup lang="ts">
import {
	SelectContent,
	SelectViewport,
	useForwardPropsEmits,
	type SelectContentEmits,
	type SelectContentProps
} from 'reka-ui';
import { injectSelect } from './context.js';

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<SelectContentProps>(), {
	position: 'popper',
	sideOffset: 4
});
const emits = defineEmits<SelectContentEmits>();
const forwarded = useForwardPropsEmits(props, emits);
const ctx = injectSelect();
</script>

<template>
	<!-- No portal: Reka positions the list with position: fixed, so it stays inside your styles. -->
	<SelectContent v-bind="forwarded" as-child>
		<div
			v-bind="$attrs"
			class="content"
			:aria-labelledby="ctx.hasLabel.value ? ctx.labelId : undefined"
		>
			<SelectViewport as-child>
				<div class="viewport"><slot /></div>
			</SelectViewport>
		</div>
	</SelectContent>
</template>

<!--
	Options you can set from a parent or on the select content itself:
	--dui-select-content-min-width, --dui-select-content-radius, --dui-select-content-bg, --dui-select-content-fg
-->

<style scoped>
/* Reka waits for animationend before removing the list, so it animates with
   the shared keyframes on [data-state]. */
.content {
	/* Reka copies this onto the positioning wrapper it puts around the list. */
	z-index: var(--dui-z-popover);
	min-width: max(var(--dui-select-content-min-width, 9rem), var(--reka-select-trigger-width));
	max-height: var(--reka-select-content-available-height);
	overflow-x: hidden;
	overflow-y: auto;
	outline: none;
	border-radius: var(--dui-select-content-radius, var(--dui-radius-md));
	background: var(--dui-select-content-bg, var(--dui-color-popover));
	color: var(--dui-select-content-fg, var(--dui-color-popover-foreground));
	box-shadow:
		0 0 0 1px color-mix(in oklch, var(--dui-color-foreground) 10%, transparent),
		var(--dui-shadow-md);

	&[data-state='open'] {
		animation: distill-zoom-in var(--dui-duration-fast) var(--dui-ease-out);
	}

	&[data-state='closed'] {
		animation: distill-zoom-out var(--dui-duration-fast) var(--dui-ease-out);
	}
}

.viewport {
	padding: var(--dui-space-1);
}
</style>
