// packages/vue/src/components/ui/select/SelectContent.vue
<script setup lang="ts">
import {
	SelectContent,
	SelectViewport,
	useForwardPropsEmits,
	type SelectContentEmits,
	type SelectContentProps
} from 'reka-ui';
import { injectSelect } from './context.js';

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<SelectContentProps>(), {
	position: 'popper',
	sideOffset: 4
});
const emits = defineEmits<SelectContentEmits>();
const forwarded = useForwardPropsEmits(props, emits);
const ctx = injectSelect();
</script>

<template>
	<!-- No portal: Reka positions the list with position: fixed, so it stays inside your styles. -->
	<SelectContent v-bind="forwarded" as-child>
		<div
			v-bind="$attrs"
			class="content"
			:aria-labelledby="ctx.hasLabel.value ? ctx.labelId : undefined"
		>
			<SelectViewport as-child>
				<div class="viewport"><slot /></div>
			</SelectViewport>
		</div>
	</SelectContent>
</template>

<!--
	Options you can set from a parent or on the select content itself:
	--dui-select-content-min-width, --dui-select-content-radius, --dui-select-content-bg, --dui-select-content-fg
-->

<style scoped>
/* Reka waits for animationend before removing the list, so it animates with
   the shared keyframes on [data-state]. */
.content {
	/* Reka copies this onto the positioning wrapper it puts around the list. */
	z-index: var(--dui-z-popover);
	min-width: max(var(--dui-select-content-min-width, 9rem), var(--reka-select-trigger-width));
	max-height: var(--reka-select-content-available-height);
	overflow-x: hidden;
	overflow-y: auto;
	outline: none;
	border-radius: var(--dui-select-content-radius, var(--dui-radius-md));
	background: var(--dui-select-content-bg, var(--dui-color-popover));
	color: var(--dui-select-content-fg, var(--dui-color-popover-foreground));
	box-shadow:
		0 0 0 1px color-mix(in oklch, var(--dui-color-foreground) 10%, transparent),
		var(--dui-shadow-md);

	&[data-state='open'] {
		animation: distill-zoom-in var(--dui-duration-fast) var(--dui-ease-out);
	}

	&[data-state='closed'] {
		animation: distill-zoom-out var(--dui-duration-fast) var(--dui-ease-out);
	}
}

.viewport {
	padding: var(--dui-space-1);
}
</style>

// packages/svelte/src/lib/components/ui/select/select-content.svelte
<script lang="ts">
	import type { HTMLAttributes } from 'svelte/elements';
	import { getSelectContext } from './context.js';

	let { class: className, children, ...restProps }: HTMLAttributes<HTMLDivElement> = $props();

	const ctx = getSelectContext();
</script>

<!-- Melt uses the native popover API (top layer), so no portal is needed. -->
<div
	{...restProps}
	{...ctx.select.content}
	aria-labelledby={ctx.hasLabel ? ctx.labelId : undefined}
	class={['content', className]}
>
	<div class="viewport">
		{@render children?.()}
	</div>
</div>

<!--
	Options you can set from a parent or on the select content itself:
	--dui-select-content-min-width, --dui-select-content-radius, --dui-select-content-bg, --dui-select-content-fg
-->

<style>
	/* Melt positions with floating-ui and the popover API; open animation uses @starting-style
	   because the popover goes from display:none, and Melt has no exit-animation hook here. */
	.content {
		margin: 0;
		padding: 0;
		border: 0;
		min-width: max(var(--dui-select-content-min-width, 9rem), var(--melt-invoker-width));
		max-height: var(--melt-popover-available-height);
		overflow-x: hidden;
		outline: none;
		overflow-y: auto;
		border-radius: var(--dui-select-content-radius, var(--dui-radius-md));
		background: var(--dui-select-content-bg, var(--dui-color-popover));
		color: var(--dui-select-content-fg, var(--dui-color-popover-foreground));
		box-shadow:
			0 0 0 1px color-mix(in oklch, var(--dui-color-foreground) 10%, transparent),
			var(--dui-shadow-md);
		transition:
			opacity var(--dui-duration-fast) var(--dui-ease-out),
			scale var(--dui-duration-fast) var(--dui-ease-out);

		@starting-style {
			opacity: 0;
			scale: 0.95;
		}
	}

	.viewport {
		padding: var(--dui-space-1);
	}
</style>
